import sqlite3 as sq

conn = sq.connect('realoffice.db')
print("Opened database successfully")
conn.execute('''CREATE TABLE VENUE
        (ID INTEGER PRIMARY KEY AUTOINCREMENT,
        VENUE_NAME TEXT NOT NULL,
        VENUE_CAP  INT  NOT NULL,
        VENUE_PROJ INT  NOT NULL,
        VENUE_AC   INT  NOT NULL);''')
conn.execute("INSERT INTO VENUE(VENUE_NAME,VENUE_CAP,VENUE_PROJ,VENUE_AC) \
        VALUES('CS14',100,1,0)");
conn.execute("INSERT INTO VENUE(VENUE_NAME,VENUE_CAP,VENUE_PROJ,VENUE_AC) \
        VALUES('CS16',100,0,0)");
conn.execute("INSERT INTO VENUE(VENUE_NAME,VENUE_CAP,VENUE_PROJ,VENUE_AC) \
        VALUES('CS24',100,1,0)");
conn.execute("INSERT INTO VENUE(VENUE_NAME,VENUE_CAP,VENUE_PROJ,VENUE_AC) \
        VALUES('CS25',150,1,1)");
conn.execute("INSERT INTO VENUE(VENUE_NAME,VENUE_CAP,VENUE_PROJ,VENUE_AC) \
        VALUES('CS26',100,1,0)");
conn.execute('''CREATE TABLE EVENT
    (ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    TYPE TEXT NOT NULL,
    HOST1 INT NOT NULL,
    MANAGER TEXT,
    PARTICIPANTS CHAR[100] NOT NULL,
    DESC CHAR[100],
    VENUE TEXT NOT NULL,
    STARTTIME TEXT NOT NULL,
    ENDTIME TEXT NOT NULL,
    PROJ INT,
    RFSHMT INT,
    STNRY INT,
    OTHER_REQ CHAR[100],
    AC INT);''')

conn.execute('''CREATE TABLE HOST
    (ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    TYPE TEXT NOT NULL,
    ROLL_NO TEXT);''')

conn.execute('''CREATE TABLE E_MANAGER
    (ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    EMAIL_ID TEXT NOT NULL);''')

conn.commit()

conn.close()
